#!/usr/bin/env bash
# Pocket Agents installer.
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/the-agents-work/pocket-agents/main/install.sh | bash
#
# Idempotent: re-running pulls the latest main, rebuilds, and re-symlinks.
# Designed for personal-laptop use — installs into $HOME, no sudo needed.
set -euo pipefail

REPO_URL="${POCKETAGENTS_REPO:-https://github.com/the-agents-work/pocket-agents.git}"
INSTALL_DIR="${POCKETAGENTS_HOME_SRC:-$HOME/.local/share/pocket-agents}"
BIN_DIR="${POCKETAGENTS_BIN_DIR:-$HOME/.local/bin}"
WRAPPER="$BIN_DIR/pocket-agents"

say() { printf '\033[1;36m==>\033[0m %s\n' "$*"; }
die() { printf '\033[1;31merror:\033[0m %s\n' "$*" >&2; exit 1; }

# 1. Ensure prerequisites: git + unzip (for the Bun installer) + Bun.
need_git() {
  command -v git >/dev/null 2>&1 || die "git not found. Install git first."
}
need_unzip() {
  command -v unzip >/dev/null 2>&1 && return
  case "$(uname -s)" in
    Linux*)
      if command -v apt-get >/dev/null 2>&1; then
        say "Installing unzip (Bun installer requires it)..."
        sudo apt-get update -qq && sudo apt-get install -y -qq unzip
      else
        die "unzip not found and no apt-get available — install unzip manually then re-run."
      fi
      ;;
    Darwin*) ;;  # macOS ships unzip
    *) die "Unsupported OS: $(uname -s)" ;;
  esac
}
ensure_bun() {
  if command -v bun >/dev/null 2>&1; then
    say "Bun $(bun --version) detected."
    return
  fi
  say "Installing Bun..."
  curl -fsSL https://bun.sh/install | bash >/dev/null
  # shellcheck source=/dev/null
  export PATH="$HOME/.bun/bin:$PATH"
  command -v bun >/dev/null 2>&1 || die "Bun install failed."
  say "Bun $(bun --version) installed at ~/.bun/bin/bun."
}

need_git
need_unzip
ensure_bun

# 2. Clone or update the repo.
if [ -d "$INSTALL_DIR/.git" ]; then
  say "Updating existing checkout at $INSTALL_DIR"
  git -C "$INSTALL_DIR" fetch --quiet origin main
  git -C "$INSTALL_DIR" reset --hard origin/main --quiet
else
  say "Cloning into $INSTALL_DIR"
  mkdir -p "$(dirname "$INSTALL_DIR")"
  git clone --depth 1 --quiet "$REPO_URL" "$INSTALL_DIR"
fi

# 3. Install + build (build emits apps/cli/dist/index.js with the right shebang).
say "Installing dependencies..."
( cd "$INSTALL_DIR" && bun install --silent )
say "Building CLI bundle..."
( cd "$INSTALL_DIR/apps/cli" && bun run build )

CLI_ENTRY="$INSTALL_DIR/apps/cli/dist/index.js"
[ -x "$CLI_ENTRY" ] || die "Build did not produce $CLI_ENTRY"

# 4. Drop a thin wrapper into $BIN_DIR so `pocket-agents` is on $PATH.
mkdir -p "$BIN_DIR"
cat > "$WRAPPER" <<EOF
#!/usr/bin/env bash
# Auto-generated by install.sh. Re-run the installer to update.
exec bun "$CLI_ENTRY" "\$@"
EOF
chmod +x "$WRAPPER"

# 5. Tell the user how to get it on PATH if needed.
case ":$PATH:" in
  *":$BIN_DIR:"*) ;;
  *)
    cat <<MSG

\033[1;33mAdd this to your shell rc (~/.bashrc or ~/.zshrc) so 'pocket-agents' is on PATH:\033[0m

    export PATH="$BIN_DIR:\$PATH"

Then open a new terminal, or run: export PATH="$BIN_DIR:\$PATH"
MSG
    ;;
esac

say "Done. Start with:  pocket-agents"
say "Or run inline:    $WRAPPER"
